---
# playbook to configure packer generated hosts
- name: First Time Configuration
  hosts: all

  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
      update_cache: yes
    become: yes

  - name: Install standard utilities
    apt:
      name:
      - vim
      - mlocate
      - bash-completion
    become: yes

  - name: Set timezone to America/New_York
    timezone:
      name: America/New_York
    become: yes

  - name: Reboot server
    reboot:
    become: yes

  #  add dns server
  